[package]
name = "folds"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.8"
num_cpus = "1.16"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "folding_benchmarks"
harness = false
